### ISSUE TITLE
Add-on fails to start

### ISSUE THREAD

**Issue by mrfixit1** [egguy/addon-grott#27]
All fine until yesterday, today the add-on doesn’t start.

Info and error message from log:
…
 Add-on version: 0.1.7
 You are running the latest version of this add-on.
 System: Home Assistant OS 11.5  (aarch64 / raspberrypi3-64)
 Home Assistant Core: 2024.2.1
 Home Assistant Supervisor: 2024.01.1
….
s6-rc: info: service legacy-services successfully started
[13:43:24] INFO: Preparing to start...
[13:43:48] ERROR: Got unexpected response from the API: Service not enabled
./script.sh: line 230: GROTT_CONFIG_MQTT_HOST: unbound variable
s6-rc: info: service legacy-services: stopping
…

The datalogger shows CONN OK. Switching it from HA back to the direct connection with server.growatt.com updates the data in the Growatt dashboard, as expected.

Anyone have any ideas how to get the add-on going again?

**Comment by egguy** [comment]
Hi, could you try to restart the mosquitto addon, then the add-on?

It seems this procedure solve this error. I still don't know the root cause, I will try to find a more definitive fix.

**Comment by mrfixit1** [comment]
Thanks for the super quick response. Unfortunately the restarts didn’t help. The error message is no longer present in the grott add-on log and all looks normal up to the first response from the Growatt server, but nothing more appears and I’m not seeing any PV data in the HA dashboard.

**Comment by mrfixit1** [comment]
Daytime update. No data this morning after the 2nd restart yesterday, or after a 3rd cycle of: stop grott - restart mosquitto - start grott. I then set the data logger back to the growatt server, stopped grott, restarted mosquitto, started grott and reset the data logger to HA; this worked!

**Comment by splitbrain** [comment]
I had the same issue. A restart of mosquitto _did_ fix it for me.
