### ISSUE TITLE
tiny bug regarding the documentation

### ISSUE THREAD

**Issue by typxxi** [egguy/addon-grott#33]
Here you can find in the readme the title Grott beta 2.7.x

which seems to be wrong cause in the following text you refer to 2.8 branch 
'This add-on is based on the 2.8 Branch of [grott](https://github.com/johanmeijer/grott) code'

Usually not a big difference, but in this case there have been big changes at least for raspi users cause from 2.8.2 onwards there is a new multi platform version being used for all devices, no more rpi edition. 

If you did not use the right code base like in my case grott:2.8.3 
you would get the latest stable which is currently 2.7.8 which is not a multiplatform version and therefore will cause an error like unsupported platform cause the raspi pi part is only available from the 2.8.2 version onwards, but not sure, could also be from 2.8.3
 onwards cause I needed a day to find this mess and identify the cause cause I had gotten 2.7.8 instead the multi platform version 2.8.3 which  I was able to install by adding :2.8.3 

Here is the link to the in my opinion misleading '2.7.8' [headline](https://github.com/egguy/addon-grott/tree/main?tab=readme-ov-file#grott-beta-27x)

great work, Etienne !

**Comment by egguy** [comment]
Hi, thanks for the bug report. 

When you say grott:2.8.3 do you refer to the docker version published by the author of grott?

I built the add-on for source and they are compatible with armv7/armhf and arm64. They use the base image from HA but the grott is built from source.
