### ISSUE TITLE
Protocoll Show me the wrong ip

### ISSUE THREAD

**Issue by derpate1989** [egguy/addon-grott#51]
Hi, 

My Home Assistant runs as Proxmox VM with 192.168.178.xxx ip range. 

The addon log show me following: 

***********************************
	 - Grott - libscrc not installed, no CRC checking only record validation on length!
	 **********************************************************************************
Hostname : 1ef934e0-grott
IP :  172.30.33.4 , port :  5279 

I dont use this IP adress. What can i do? Can i change the ip adress in groot config? 

Btw, my growatt Neo can not find my HA Server.

**Comment by egguy** [comment]
Hi,

This is the IP used by grott in the container. It doesn't affect how it works. The container has its own network stack but HA port forward to grott

To get the correct IP to put into the data logger you can use the guide here to find it: https://github.com/egguy/addon-grott/blob/main/grott/DOCS.md#configuration-of-the-wi-fi-logger
