### ISSUE TITLE
Home Assistant Grott Plugin Not Working: Server IP Resetting to Default

### ISSUE THREAD

**Issue by koopee** [egguy/addon-grott#57]
Issue:
My Home Assistant Grott plugin has stopped functioning correctly. When I set the server IP in the Shinewifi-X configuration, it automatically changes back to the default Grott server after a few minutes, causing the proxy to stop working. This behaviour started yesterday. The integration/proxy has worked previously normally for months

Steps to Reproduce:

    Open Shinewifi-X configuration settings.
    Set the desired server IP.
    Save the configuration.
    Observe that the server IP resets to the default Grott server.

Expected Behavior:
The server IP should remain as configured and not revert to the default Grott server.

Actual Behavior:
The server IP reverts to the default Grott server, causing the proxy to fail.

Environment:

    Home Assistant version:
     - Core 2024.7.2
     - Supervisor 2024.06.2
     - Operating System 12.4
     - Frontend 20240710.0
    Grott plugin version: Grott stable branch (2.8)
    Grott - Home Assistant native MQTT integration: Current version: 0.1.10 (Changelog)

    ShineWifiX Firmware Version：3.1.0.5

Please let me know if further information is required to troubleshoot this problem.

**Comment by egguy** [comment]
It is probably related to: https://github.com/egguy/addon-grott-beta/issues/51#issuecomment-2231910621
