### ISSUE TITLE
After update to 0.1.11 add-on not working anymore

### ISSUE THREAD

**Issue by thoompje** [egguy/addon-grott#75]
Hello All,

After updating this morning from 0.1.10 to  0.1.11, the add-on is not working anymore. This is the log:

> Traceback (most recent call last):
>   File "/app/grott.py", line 35, in <module>
>     proxy.main(conf)
>   File "/app/grottproxy.py", line 129, in main
>     inputready, outputready, exceptready = ss(self.input_list, [], [])
>                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
> ValueError: filedescriptor out of range in select()
> s6-rc: info: service legacy-services: stopping
> s6-rc: info: service legacy-services successfully stopped
> s6-rc: info: service legacy-cont-init: stopping
> s6-rc: info: service legacy-cont-init successfully stopped
> s6-rc: info: service fix-attrs: stopping
> s6-rc: info: service base-addon-log-level: stopping
> s6-rc: info: service base-addon-log-level successfully stopped
> s6-rc: info: service fix-attrs successfully stopped
> s6-rc: info: service base-addon-banner: stopping
> s6-rc: info: service base-addon-banner successfully stopped
> s6-rc: info: service s6rc-oneshot-runner: stopping
> s6-rc: info: service s6rc-oneshot-runner successfully stopped

Anyone any idea?

_I have restored a back-up tot 0.1.10 and it's working again, so now I'll wait to update when there is a fix. Anyone else with the same issue?_

**Comment by larrybml** [comment]
Yes, same problem here. It starts and after short time is stopping itself. Even I start it again , it is stopping itself again, and mqtt does not receive any data. Waiting also for a fix.

**Comment by egguy** [comment]
O_o I'm going to take a look. It seems other users are affected: https://github.com/johanmeijer/grott/issues/341

**Comment by larrybml** [comment]
Same fault, I just updated again, but same issue , it starts and after that it is shutting down by itself with the folowing log :

ValueError: filedescriptor out of range in select()
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service base-addon-log-level: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service base-addon-log-level successfully stopped
s6-rc: info: service base-addon-banner: stopping
s6-rc: info: service base-addon-banner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
s6-svscanctl: fatal: unable to control /run/service: supervisor not listening


Just returned back to 0.1.10
