### ISSUE TITLE
Support for Growatt ShineWifi X2

### ISSUE THREAD

**Issue by jafar-atili** [egguy/addon-grott#88]
I have just installed a Growatt Hybrid inverter.

I received the ShineWifi X2 and the server configuration doesn't seems to allow changing the port from 7006:

![image](https://github.com/user-attachments/assets/d30256e8-b6f8-4a96-85d1-b78e0fdd6cf1)

I tried changing the Grott Addons port to 7006 but it still comes up either tje default port (5279)

And I am not sure if the integration even expecting an MQTT packet as the default domain seems to be MQTT.

My inverter is MID 11-30KTL3-XH

**Comment by egguy** [comment]
Hi,

The addon system in HA allows you to do port redirect without reconfiguration of grott. You can change the port in the port configuration: 
![image](https://github.com/user-attachments/assets/9d8bd7b0-8b8b-4e18-9209-6921f20abf87)

And even if grott still displays 5279, the HA interface will listen on 7006 and forward to the 5279 port in the addon.

As for this stick and MQTT I don't think this add-on process MQTT.

**Comment by jafar-atili** [comment]
I did that and I got invalid packet in the log...
