### ISSUE TITLE
Setting registers

### ISSUE THREAD

**Issue by sceife** [egguy/addon-grott#89]
Hello,

So far, Grott is working very well for me. I receive information from my inverter SPH 3500ES in the Growatt APP and in Homeassistant. Through the APP or the homepage, I have the possibility to change registers.

My goal is to charge my battery depending on the sunlight. For this, I can change a specific register, and then the charging power changes.

Will this be implemented in future releases?

Thank you very much.

**Comment by typxxi** [comment]
If I remember right muppet3000 has announced something like this in spring that he would be working on such features cause he has the same issues.

I have 8 inverters and only 2 hybrids SPH 4600. I could charge onlly via DC from the SPH 4600 strings into each of the battery.

If I change the inverter settings to charge also AC then both SPH 4600 would also take AC power to charge the battery, but in such a case it could be that the panels deliver 1000 Watt, while I have also 1000W surplus AC available but the growatt inverters will then also take 1000 W from the grid to charge cause they cannot only detect and limit the use of AC what I am feeding in. 

Therefore I have to reduce the charging power while AC charging is enabled to a figure that minimises the AC from the grid like in this case 1000 Watt DC and 1000 Watt AC which is 2000 W and that means 66% cause the SPH can only charge up to 3000W. If I want to limit the charging to 2000W then I have to that via the 66% which is roughly 2000W 

ANd then I would have to change that % every few minutes or so ...

But this can only work as an automation and not really manually. That is why I am waiting for an alternativ modbus integration in HA or via ESPHOME which I have seen somewhere.
